# Generated by Django 4.0.3 on 2022-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_loan',
        ),
        migrations.AddField(
            model_name='account',
            name='loan',
            field=models.BooleanField(default=False),
        ),
    ]
